name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Deploy to EC2
      env:
        EC2_HOST: "ec2-18-117-153-215.us-east-2.compute.amazonaws.com" # Replace with your EC2 public DNS
        EC2_USER: "ubuntu" # Adjust if your EC2 instance uses a different username
      run: |
        # Save the private key
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem

        # Ensure the key has the correct permissions
        chmod 600 ec2_key.pem

        # Test SSH connection
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST "echo 'SSH connection successful'"

        # Deploy the project
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
        set -e

        # Navigate to project directory (create if doesn't exist)
        cd ~/django_project || mkdir ~/django_project && cd ~/django_project

        # Pull latest code from GitHub
        git init  # If the project isn't already a git repo
        git remote add origin https://github.com/<your-username>/<your-repository>.git || true
        git fetch --all
        git reset --hard origin/main

        # Set up Python virtual environment
        source venv/bin/activate || python3 -m venv venv && source venv/bin/activate

        # Install dependencies
        pip install --upgrade pip
        pip install -r requirements.txt

        # Apply migrations and collect static files
        python3 manage.py migrate
        python3 manage.py collectstatic --noinput

        # Restart Gunicorn and Nginx
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx
        EOF
